// practice/JavaScript/React/framework-compare/src/components/ResourceSearch.js
const ResourceSearch = () => {
  return (
    <form className="card p-2">
      <div className="input-group">
        <input type="text" className="form-control" placeholder="Some title" />
        <div className="input-group-append">
          <button type="submit" className="btn btn-secondary">
            Search
          </button>
        </div>
      </div>
    </form>
  );
};

export default ResourceSearch;

// practice/JavaScript/Vue/framework-compare-vue-3/src/components/ResourceSearch.vue
<template>
  <form class="card p-2">
    <div class="input-group">
      <input type="text" class="form-control" placeholder="Some title" />
      <div class="input-group-append">
        <button type="submit" class="btn btn-secondary">Search</button>
      </div>
    </div>
  </form>
</template>

<script>
export default {};
</script>
