// practice/JavaScript/React/framework-compare/src/components/ResourceList.js
const ResourceList = ({ resources }) => {
  return (
    <ul className="list-group mb-3 resource-list">
      {resources.map((resources) => (
        <li
          key={resources._id}
          className="list-group-item d-flex justify-content-between lh-condensed"
        >
          <div>
            <h6 className="my-0">{resources.title}</h6>
            <small className="text-muted">{resources.description}</small>
          </div>
          <span className="text-muted">{resources.type}</span>
        </li>
      ))}
    </ul>
  );
};

export default ResourceList;

// practice/JavaScript/Vue/framework-compare-vue-3/src/components/ResourceList.vue
<template>
  <ul class="list-group mb-3">
    <li
      v-for="resource in resources"
      :key="resource._id"
      class="list-group-item d-flex justify-content-between lh-condensed"
    >
      <div>
        <h6 class="my-0">{{ resource.title }}</h6>
        <small class="text-muted">{{ resource.description }}</small>
      </div>
      <span class="text-muted">{{ resource.type }}</span>
    </li>
  </ul>
</template>

<script>
export default {
  props: {
    resources: {
      type: Array,
      default: () => [],
    },
  },
};
</script>
