// practice/JavaScript/Vue/framework-compare-vue-3/src/components/ResourceDetail.vue
<template>
  <div class="card">
    <div class="card-header">
      Resource Name
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p>Resource description...</p>
        <footer class="text-muted mb-2">Type</footer>
      </blockquote>
      <a href="#" class="btn btn-primary">Edit</a>
    </div>
  </div>
</template>

<script>
export default {};
</script>

// practice/JavaScript/React/framework-compare/src/components/ResourceDetail.js
const ResourceDetail = () => {
  return (
    <>
      <h4 className="mb-3">Update Resource</h4>
      <div className="card">
        <div className="card-header">Resource Name</div>
        <div className="card-body">
          <blockquote className="blockquote mb-0">
            <p>Resource description...</p>
            <footer className="text-muted mb-2">Type</footer>
          </blockquote>
          <a href="#" className="btn btn-primary">
            Edit
          </a>
        </div>
      </div>
    </>
  );
};

export default ResourceDetail;
