// practice/JavaScript/Vue/framework-compare-vue-3/src/components/ResourceForm.vue
<template>
  <form @submit.prevent="submitForm">
    <div v-if="alert?.success" class="alert alert-success">
      {{ alert.success }}
    </div>
    <div v-if="alert?.error" class="alert alert-danger">
      {{ alert.error }}
    </div>
    <div class="mb-3">
      <label htmlFor="firstName">Title</label>
      <input
        v-model="uResource.title"
        type="text"
        class="form-control"
        id="firstName"
        placeholder="How to survice in mountains"
      />
    </div>
    <div class="mb-3">
      <label for="description">Description</label>
      <textarea
        v-model="uResource.description"
        class="form-control"
        id="description"
        placeholder="Just some description"
      ></textarea>
    </div>
    <div class="mb-3">
      <label htmlFor="link">Resource Link</label>
      <div class="input-group">
        <input
          v-model="uResource.link"
          type="text"
          class="form-control"
          id="link"
          placeholder="Username"
        />
      </div>
    </div>
    <div class="mb-3">
      <label htmlFor="link">Type</label>
      <select v-model="uResource.type" id="link" class="form-control">
        <option
          v-for="resourceType in types"
          :key="resourceType"
          :value="resourceType"
          >{{ resourceType }}</option
        >
      </select>
    </div>
    <hr class="mb-4" />
    <button class="btn btn-primary btn-lg btn-block" type="submit">
      Submit
    </button>
  </form>
</template>

<script>
export default {
  props: {
    resource: Object,
    alert: Object
  },
  data() {
    return {
      uResource: { ...this.resource },
      types: ['blog', 'video', 'book'],
    };
  },
  emits: ['on-form-submit'],
  watch: {
    resource(newResource) {
      this.uResource = { ...newResource };
    },
  },
  methods: {
    submitForm() {
      this.$emit('on-form-submit', this.uResource);
    },
  },
};
</script>

// practice/JavaScript/React/framework-compare/src/components/ResourceForm.js
import { useState } from 'react';

const RESOURCE_TYPES = ['blog', 'video', 'book'];

const ResourceForm = ({ resource, onSumbit }) => {
  const [uResource, setUResource] = useState(resource);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setUResource({ ...uResource, [name]: value });
  };

  const handleSubmit = () => {
    onSumbit(uResource);
  };

  return (
    <form>
      <div className="mb-3">
        <label htmlFor="title">Title</label>
        <input
          onChange={handleChange}
          value={uResource.title}
          name="title"
          type="text"
          className="form-control"
          id="title"
          placeholder="How to survice in mountains"
        />
      </div>
      <div className="mb-3">
        <label htmlFor="description">Description</label>
        <textarea
          onChange={handleChange}
          value={uResource.description}
          name="description"
          className="form-control"
          id="description"
          placeholder="Just some description"
        ></textarea>
      </div>

      <div className="mb-3">
        <label htmlFor="link">Resource Link</label>
        <div className="input-group">
          <input
            onChange={handleChange}
            value={uResource.link}
            name="link"
            type="text"
            className="form-control"
            id="link"
            placeholder="Username"
          />
        </div>
      </div>
      <div className="mb-3">
        <label htmlFor="type">Type</label>
        <select
          className="form-control"
          name="type"
          value={uResource.type}
          onChange={handleChange}
          id="type"
        >
          {RESOURCE_TYPES.map((type) => (
            <option key={type} value={type}>
              {type}
            </option>
          ))}
        </select>
      </div>
      <hr className="mb-4" />
      <button
        onClick={handleSubmit}
        className="btn btn-primary btn-lg btn-block"
        type="button"
      >
        Submit
      </button>
    </form>
  );
};

export default ResourceForm;
