// practice/JavaScript/Vue/framework-compare-vue-3/src/pages/ResourceHome.vue
<template>
  <div class="container">
    <resource-header />
    <div class="row">
      <div class="col-md-4 order-md-2 mb-4">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-muted">Your Resources</span>
          <span class="badge badge-secondary badge-pill">{{
            resourcesLength
          }}</span>
        </h4>
        <resource-search />
        <resource-list :resources="resources" />
      </div>
      <div class="col-md-8 order-md-1">
        <h4 class="mb-3">
          Resource
          <button @click="toggleView" class="btn btn-sm btn-success">
            Toggle
          </button>
        </h4>
        <resource-detail v-if="isDetailView" />
        <resource-update v-else />
      </div>
    </div>
  </div>
</template>

<script>
import ResourceHeader from '@/components/Header';
import ResourceSearch from '@/components/ResourceSearch';
import ResourceList from '@/components/ResourceList';
import ResourceUpdate from '@/components/ResourceUpdate';
import ResourceDetail from '@/components/ResourceDetail';
export default {
  components: {
    ResourceHeader,
    ResourceSearch,
    ResourceList,
    ResourceUpdate,
    ResourceDetail,
  },
  data() {
    return {
      isDetailView: true,
      resources: [
        {
          _id: '1',
          title: 'Resource 1 Title',
          description: 'Resource 1 Description',
          type: 'video',
          link: '',
        },
        {
          _id: '2',
          title: 'Resource 2 Title',
          description: 'Resource 2 Description',
          type: 'book',
          link: '',
        },
        {
          _id: '3',
          title: 'Resource 3 Title',
          description: 'Resource 3 Description',
          type: 'blog',
          link: '',
        },
      ],
    };
  },
  computed: {
    // it will be re-evaluated every time reactive dependency will change
    resourcesLength() {
      return this.resources.length;
    },
  },
  methods: {
    // it will be re-evaluated every time
    getResourceLength() {
      return this.resources.length;
    },
    toggleView() {
      this.isDetailView = !this.isDetailView;
    },
  },
};
</script>

// practice/JavaScript/React/framework-compare/src/pages/ResourceHome.js
import { useState } from 'react';

import ResourceSearch from '../components/ResourceSearch';
import ResourceList from '../components/ResourceList';
import ResourceDetail from '../components/ResourceDetail';
import ResourceUpdate from '../components/ResourceUpdate';
import Header from '../components/Header';

const initialResources = [
  {
    _id: '1',
    title: 'resource 1',
    description: 'Description 1',
    link: 'https://google.com',
    type: 'blog',
  },
  {
    _id: '2',
    title: 'resource 2',
    description: 'Description 2',
    link: 'https://google.com',
    type: 'video',
  },
  {
    _id: '3',
    title: 'resource 3',
    description: 'Description 3',
    link: 'https://google.com',
    type: 'book',
  },
];

const ResourceHome = () => {
  const [resources, setResources] = useState(initialResources);
  const [isDetailView, setDetailView] = useState(true);

  const addResource = () => {
    const _id = '_' + Math.random().toString(36).substr(2, 9);
    const newSource = {
      _id,
      title: `Title ${_id}`,
      description: `Description ${_id}`,
      link: 'https://google.com',
      type: 'video',
    };

    setResources([newSource, ...resources]);
  };

  return (
    <div className="container">
      <Header />
      <div className="row">
        <div className="col-md-4 order-md-2 mb-4">
          <h4 className="d-flex justify-content-between align-items-center mb-3">
            <span className="text-muted">Your Resources</span>
            <span className="badge badge-secondary badge-pill">6</span>
          </h4>
          <ResourceSearch />
          <ResourceList resources={resources} />
          <button onClick={addResource} className="btn btn-primary">
            Add Resource
          </button>
        </div>
        <div className="col-md-8 order-md-1">
          {isDetailView ? (
            <ResourceDetail onButtonClick={() => setDetailView(false)} />
          ) : (
            <ResourceUpdate />
          )}
        </div>
      </div>
    </div>
  );
};

export default ResourceHome;
